ignore:
  - "samples/**/*"
  - "tests/**/*"

coverage:
  range: 40..90
  round: nearest
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true

comment: false
